import Head from "next/head";
import Featured from "../components/Banner/Featured";
import AllCategories from "../components/Categories/AllCategories";
import SpecialOffer from "../components/Common/SpecialOffer";
import FeaturedProducts from "../components/Products/FeaturedProducts";
import RecentProducts from "../components/Products/RecentProducts";
import dynamic from "next/dynamic";
import axios from "axios";

const VendorCarousel = dynamic(
  () => import("../components/Common/VendorCarousel"),
  {
    ssr: false,
  }
);

const BannerCarousel = dynamic(
  () => import("../components/Banner/BannerCarousel"),
  {
    ssr: false,
  }
);
export default function Home({ categories, featured, recentProducts }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <BannerCarousel />
      <Featured />
      <AllCategories categories={categories} />
      <FeaturedProducts featured={featured}/>
      <SpecialOffer />
      <RecentProducts recentProducts={recentProducts}/>
      <VendorCarousel />      
    </div>
  );
}

export const getServerSideProps = async () => {
  const resCategories = await axios.get(
    "https://wpfurniture.mangoitsol.com/wp-json/wc/store/products/categories"
  );
  const resFeatured = await axios.get("https://wpfurniture.mangoitsol.com/wp-json/wc/store/products?featured=true");
  const resProducts = await axios.get("https://wpfurniture.mangoitsol.com/wp-json/wc/store/products?orderby=date&order=asc");
  const categories = resCategories.data;
  const featured = resFeatured.data;
  const recentProducts = resProducts.data;
  return {
    props: {
      categories,
      featured,
      recentProducts
    },
  };
};
